server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev

---
server:
  servlet:
    port: 8080


spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: 
    driver: org.mariadb.jdbc.Driver
    username: 
    password: 
  jpa:
    database: mariadb
    database-platform: 
    show-sql: true
    generate-ddl: true
    hibernate: 
      ddl-update: auto

logging:
  file:
    path: /log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    me.hong.kotlinspring: debug